export const SHAREDPREFS_NAME = "RONIN_SHAREDPREFS";
export const KEYCHAIN_SERVICE = "RONIN_KEYSERVICE";

export const SYNC_STATUS_VERIFY = 1000; // Time Interval

export const KEY_NAME = {
  ORG_USER_ACCESS_TOKEN: "orgUserAccessToken",
  ORG_ID: "organizationId",
  EVENT_ID: "organizerEventId",
  EMP_USER_ACCESS_TOKEN: "employeeUserAccessToken",
  SELECTED_LOCATION: "selectedlocation",
  SELECTED_MENU: "selectedMenu",
  EVENTS_SYNC: "eventsSync",
  USERS_SYNC: "usersSync",
  DISCOUNTS_SYNC: "discountsSync",
  LOCATIONS_SYNC: "locationsSync",
  MENUS_SYNC: "menusSync",
  MENU_ITEMS_SYNC: "menuItemsSync",
  ATTENDEES_SYNC: "attendeesSync",
  RFID_SYNC: "rfidSync",
};

export const SCREEN_NAME = {
  COMPANY_LOGIN: "CompanyLogin",
  ORGANIZER_CONFIG: "OrganizerConfig",
  USER_LOGIN: "UserLogin",
  POS_CONFIG: "PosConfig",
  MENU: "Menu",
  EDIT_ORDER: "EditOrder",
  CUSTOM_ITEM: "CreateCustomItem",
  ORDER_HISTORY: "OrderHistory",
  TENDERED_AMOUNT_STEP_CASH: "TenderedAmountStepCash",
  APPROVED_STEP: "ApprovedStepCash",
  ENTER_PHONE_NUMBER_STEP_CASH: "EnterPhoneNumberStepCash",
  TRANSACTION_COMPLETED_STEP_CASH: "TransactionCompletedStepCash",
  TIP_STEP_CREDIT: "TipStepCredit",
  CREDIT_START: "CreditStart",
  ENTER_PHONE_NUMBER_STEP_CREDIT: "EnterPhoneNumberStepCredit",
  TRANSACTION_COMPLETED_STEP_CREDIT: "TransactionCompletedStepCredit",
  TIP_STEP_RFID: "TipStepRfid",
  READER_READY: "ReaderReady",
  RFID: "RFID",
  REGISTER_RFID_ASSOCIATION: "RegisterRfidAssociation",
  PIN_INSERT: "PinInsert",
  TRANSACTION_RFID_DECLINED: "TransactionRfidDeclined",
  TRANSACTION_RFID_APPROVED: "TransactionRfidApproved",
  TRANSACTION_COMPLETED_RFID: "TransactionRfidComplete",
  TIP_STEP_QR_CODE: "TipStepQRCode",
  QR_CODE_READER_READY:"QRCodeReaderReady",
  QRCODE: "QRCode",
  TRANSACTION_QRCODE_DECLINED: "TransactionQRCodeDeclined",
  TRANSACTION_QRCODE_APPROVED: "TransactionQRCodeApproved",
  TRANSACTION_COMPLETED_QRCODE: "TransactionQRCodeComplete",
  QR_CODE_SCANNER: "QrCodeScanner",
  USER_PASSCODE: "UserPasscode",
  ADMIN_PANEL: "AdminPanel",
  TICKET_REDEMPTION: "TicketRedemption",
  SCANING_SCREEN: "ScaningScreen",
  TOKEN_REDEEM_SUCCESS_FAIL: "TokenRedeemSuccessFail",
};
