export default {
  tortoise_15: require("../assets/images/tortoise_15.png"),
  fish_18: require("../assets/images/fish_18.png"),
  octopus_20: require("../assets/images/octopus_20.png"),
  favourite: require("../assets/images/favourite.png"),
  unFavourite: require("../assets/images/unFavourite.png"),
  minuse: require("../assets/images/minuse.png"),
  setting: require("../assets/images/setting.png"),
  checkmark_circle_outline: require("../assets/images/checkmark_circle_outline.png"),
  alert_triangle_outline: require("../assets/images/alert_triangle_outline.png"),
  question_mark_circle_outline: require("../assets/images/question_mark_circle_outline.png"),
  creditCard: require("../assets/images/creditCard.png"),
  search: require("../assets/images/search.png"),
  close: require("../assets/images/close.png"),
  offlineWifi: require("../assets/images/offlineWifi.png"),
  tax: require("../assets/images/tax.png"),
  qrCodeScanner: require("../assets/images/scanner.png"),
  addCircle: require("../assets/images/add.png"),
  minusCircle: require("../assets/images/minus.png"),
  pencilSquare: require("../assets/images/pencilSquare.png"),
  checkmark_full_circle: require("../assets/images/checkmark_full_circle.png"),
  failed_circle: require("../assets/images/failed_circle.png"),
};
